version: "3"

services:
  backend:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - config/app/.env
  
  redis:
    image: redis:alpine
    ports: 
      - 6379:6379